Fix traceback in some listings because of #118
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.app.listing.view, line 248, in __call__
  Module senaite.app.listing.ajax, line 114, in handle_subpath
  Module senaite.core.decorators, line 40, in decorator
  Module senaite.app.listing.decorators, line 63, in wrapper
  Module senaite.app.listing.decorators, line 50, in wrapper
  Module senaite.app.listing.decorators, line 100, in wrapper
  Module senaite.app.listing.ajax, line 467, in ajax_folderitems
  Module senaite.app.listing.decorators, line 88, in wrapper
  Module senaite.app.listing.ajax, line 343, in get_folderitems
  Module palau.lims.browser.views.astresults, line 65, in folderitems
  Module senaite.ast.browser.results, line 179, in folderitems
  Module senaite.app.listing.view, line 950, in folderitems
  Module senaite.app.listing.view, line 758, in _fetch_brains
  Module senaite.app.listing.view, line 807, in search
  Module senaite.app.listing.view, line 614, in get_catalog_query
AttributeError: 'str' object has no attribute 'get'

```